name: Build Signed Pineapple APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Create gradle.properties with Reddit Client Secret
      run: |
        echo "ClientSecret=\"${{ secrets.REDDIT_CLIENT_SECRET }}\"" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Clean project
      run: ./gradlew clean
    
    - name: Build Debug APK (Auto-signed)
      run: ./gradlew assembleDebug
    
    - name: Build Release APK (Unsigned)
      run: ./gradlew assembleRelease
    
    - name: Sign Release APK with Debug Key
      run: |
        # Use Android SDK's debug keystore to sign the release APK
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
          --ks ~/.android/debug.keystore \
          --ks-key-alias androiddebugkey \
          --ks-pass pass:android \
          --key-pass pass:android \
          --out app/build/outputs/apk/release/pineapple-release-signed.apk \
          app/build/outputs/apk/release/*.apk
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: pineapple-debug-apk
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload Signed Release APK
      uses: actions/upload-artifact@v4
      with:
        name: pineapple-release-signed-apk
        path: app/build/outputs/apk/release/pineapple-release-signed.apk
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload Unsigned Release APK
      uses: actions/upload-artifact@v4
      with:
        name: pineapple-release-unsigned-apk
        path: app/build/outputs/apk/release/*.apk
        retention-days: 30
        if-no-files-found: warn
